version: '3.7'

services:
  front-end:
    build:
      context: https://github.com/markokrizan/upravljanje-dokumentima-fe.git
      dockerfile: Dockerfile
    ports:
      - "80:80"

  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
      - elasticsearch
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mail-app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
       - ./src/main/java:/app/main/java
       - ./src/main/resources:/app/main/resources
    networks: 
     - backend

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    environment: 
      - cluster.name=mail-app-es-cluster-1
      - node.name=mail-app-es-node-1
      - node.master=true
      - cluster.initial_master_nodes=mail-app-es-node-1
      - discovery.seed_hosts=mail-app-es-node-1
      - http.cors.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend  
    ports:
      - 9200:9200

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: mail-app
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
volumes:
  db-data:
  elasticsearch-data:

networks:
  backend:
